config/routes.rb
Howto::Application.routes.draw do
  root :to =>"tutorials#index"

  resources :tutorials do
    resources :steps
  end

end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :list, :parent_id
  belongs_to :tutorial
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  attr_accessible :list
  has_many :steps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  # GET /steps
  # GET /steps.json
  before_filter :load_tutorial

  def index
    @steps = @tutorial.steps.all
  end

  # GET /steps/1
  # GET /steps/1.json
  def show
    @step = @tutorial.steps.find(params[:id])
  end

  # GET /steps/new
  # GET /steps/new.json
  def new
    @step = @tutorial.steps.new
  end

  # GET /steps/1/edit
  def edit
    @step = @tutorial.steps.find(params[:id])
  end

  # POST /steps
  # POST /steps.json
  def create
    @step = @tutorial.steps.new(params[:step])

    respond_to do |format|
      if @step.save
        format.html { redirect_to [@tutorial, @step], notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /steps/1
  # PUT /steps/1.json
  def update
    @step = @tutorial.steps.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to [@tutorial, @step], notice: 'Step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    @step = @tutorial.steps.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to tutorial_steps_path(@tutorial) }
      format.json { head :no_content }
    end
  end

  private

  def load_tutorial
    @tutorial = Tutorial.find(params[:tutorial_id])
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.all
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tutorial }
    end
  end

  # GET /tutorials/new
  # GET /tutorials/new.json
  def new
    @tutorial = Tutorial.new
  end

  # GET /tutorials/1/edit
  def edit
    @tutorial = Tutorial.find(params[:id])
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.create!(params[:tutorial])
    respond_to do |format|
      format.html { redirect_to tutorials_url }
      format.js
    end
  end

  # PUT /tutorials/1
  # PUT /tutorials/1.json
  def update
    @tutorial = Tutorial.find(params[:id])

    respond_to do |format|
      if @tutorial.update_attributes(params[:tutorial])
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy

    respond_to do |format|
      format.html { redirect_to tutorials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/application/_side.html.erb
<strong>Navigation</strong>
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "New Tutorial", new_tutorial_path, id: "new_list", remote: true %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Howto</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="side">
    <%= render "side" %>
  </div>

  <%= yield %>

</body>
</html>

app/views/steps/_form.html.erb
<%= form_for([@tutorial, @step]) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list %><br />
    <%= f.text_field :list %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing Step</h1>

<%= render 'form' %>

<%= link_to 'Show', tutorial_step_path(@tutorial, @step) %> |
<%= link_to 'Back', tutorial_steps_path(@tutorial) %>

app/views/steps/index.html.erb
<h1><%= @tutorial.list =%></h1>

<table>
  <tr>
    <th>Steps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.list %></td>
    <td><%= link_to 'Show', tutorial_step_path(@tutorial, step) %></td>
    <td><%= link_to 'Edit', edit_tutorial_step_path(@tutorial, step) %></td>
    <td><%= link_to 'Destroy', [@tutorial, step], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_tutorial_step_path(@tutorial) %> |
<%= link_to 'Tutorial Index', tutorials_path %>

app/views/steps/new.html.erb
<h1>New Step</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorial_steps_path(@tutorial) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @step.list %>
</p>


<%= link_to 'Edit', edit_tutorial_step_path(@tutorial, @step) %> |
<%= link_to 'Back', tutorial_steps_path(@tutorial) %>

app/views/tutorials/_form.html.erb
<%= form_for @tutorial, remote: true do |f| %>
  <% if @tutorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutorial.errors.count, "error") %> prohibited this tutorial from being saved:</h2>

      <ul>
      <% @tutorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list %><br />
    <%= f.text_field :list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutorials/_tutorial.html.erb
<%= form_for tutorial, remote: true do |f| %>
  <%= tutorial.list %>
  <%= link_to 'Steps', tutorial_steps_path(tutorial) %>
  <%= link_to 'Edit', edit_tutorial_path(tutorial) %>
  <%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/tutorials/create.js.erb
$('#new_tutorial').remove();
$('#new_list').show();
$('#all_lists').append('<%= j render(@tutorial) %>');

app/views/tutorials/edit.html.erb
<h1>Editing tutorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>

app/views/tutorials/index.html.erb
<h1>Tutorials</h1>

<br />

<div id="all_lists">
  <%= render @tutorials %>
<div>

app/views/tutorials/new.html.erb
<h1>New tutorial</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorials_path %>

app/views/tutorials/new.js.erb
$('#new_list').hide().after('<%= j render("form") %>');

app/views/tutorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tutorial:</b>
  <%= @tutorial.list %>
</p>

<%= link_to 'Steps', tutorial_steps_path(@tutorial) %> |
<%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>